spring:
  application:
    name: dmatch-server
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---
